/* NONNA Gestão: pedidos vêm do DB existente; estoque e despesas usam Firebase
   nos ambientes configurados e localStorage como fallback isolado deste módulo. */
(function(){'use strict';
const $=id=>document.getElementById(id), money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEYS={stock:'nonna_gestao_estoque',moves:'nonna_gestao_movimentos',expenses:'nonna_gestao_despesas',reservations:'nonna_gestao_reservas'}; let stock=[],moves=[],expenses=[],reservations=[],orders=[],cash=null,period='30', remote=false, reportChannel='all', reportStatus='all';
const read=k=>{try{return JSON.parse(localStorage.getItem(KEYS[k])||'[]')}catch(e){return[]}}, write=(k,v)=>localStorage.setItem(KEYS[k],JSON.stringify(v));
const amount=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null}, shown=(v,available)=>available?money(v):'Sem dados';
function dateOf(o){return new Date(o.criadoEm||o.createdAt||o.data||0)} function inPeriod(d){if(!(d instanceof Date)||!Number.isFinite(d.getTime()))return false;if(period==='all')return true;const days=period==='today'?1:Number(period), start=new Date();start.setHours(0,0,0,0);if(days>1)start.setDate(start.getDate()-days+1);return d>=start}
function validOrders(){return orders.filter(o=>inPeriod(dateOf(o)))} function delivered(o){return ['entregue','concluido','finalizado'].includes(String(o.status||'').toLowerCase())}
function orderRevenue(list){return list.reduce((x,o)=>{const n=amount(o.total);return n===null?x:x+n},0)}
function loadLocal(){stock=read('stock');moves=read('moves');expenses=read('expenses');reservations=read('reservations');cash=DB&&DB.getCaixaAtual?DB.getCaixaAtual():null}
async function sync(){orders=(window.DB&&DB.getPedidos)?(DB.getPedidos()||[]):[];cash=window.DB&&DB.getCaixaAtual?DB.getCaixaAtual():null;if(window.firebase&&DB&&DB.backend==='firebase'){remote=true;try{const [s,m,e,r,c]=await Promise.all(['estoque','movimentacoes','despesas','reservas'].map(p=>firebase.database().ref('gestao/'+p).once('value')).concat(firebase.database().ref('caixa/atual').once('value')));stock=Object.values(s.val()||{});moves=Object.values(m.val()||{});expenses=Object.values(e.val()||{});reservations=Object.values(r.val()||{});cash=c.val()||null;}catch(err){loadLocal();remote=false}}else loadLocal();$('connection').textContent=remote?'● sincronizado':'● modo local';renderAll()}
async function save(kind,arr){const path={stock:'estoque',movements:'movimentacoes',moves:'movimentacoes',expenses:'despesas',reservations:'reservas'}[kind];if(remote){const obj={};arr.forEach(x=>obj[x.id]=x);await firebase.database().ref('gestao/'+path).set(obj);if(kind==='expenses' && window.DBRemote?.registrarFinanceiro){const ultimo=arr[arr.length-1];if(ultimo)try{await DBRemote.registrarFinanceiro({tipo:'despesa',origem:'gestao',valor:Number(ultimo.valor||0),categoria:ultimo.categoria,descricao:ultimo.descricao,referencia:ultimo.id,status:ultimo.paga?'pago':'pendente'})}catch(e){console.warn('[NONNA] financeiro',e.message)} } }else write(kind,arr);renderAll()}
function renderAll(){const os=validOrders(), done=os.filter(delivered), revenue=orderRevenue(done), revenueAvailable=done.some(o=>amount(o.total)!==null);$('mVendas').textContent=shown(revenue,revenueAvailable);$('mPedidos').textContent=os.length+' pedidos no período';$('mConcluidos').textContent=done.length;$('mTicket').textContent=shown(revenue/done.length,revenueAvailable&&done.length>0);const low=stock.filter(x=>Number(x.saldo||0)<=Number(x.minimo||0));$('mEstoque').textContent=stock.reduce((s,x)=>s+Number(x.saldo||0),0);$('mBaixo').textContent=low.length?low.length+' item(ns) abaixo do mínimo':'Nenhum alerta';renderChart(os);renderStatuses(os);renderStock();renderMoves();renderExpenses();renderReservations();renderReportFilters(os);renderReports(os,done,revenue)}
function renderChart(os){const days=period==='today'?1:period==='all'?14:Number(period);const arr=[];for(let i=days-1;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);arr.push({d,n:os.filter(o=>delivered(o)&&dateOf(o).toDateString()===d.toDateString()).reduce((s,o)=>s+(amount(o.total)||0),0)})}const max=Math.max(...arr.map(x=>x.n),1);$('salesChart').innerHTML=arr.map(x=>`<div class="bar" style="height:${Math.max(4,x.n/max*175)}px" title="${money(x.n)}"><em>${x.n?money(x.n):''}</em><small>${x.d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</small></div>`).join('')}
function renderStatuses(os){const counts={novo:0,preparando:0,pronto:0,em_entrega:0,cancelado:0};os.forEach(o=>{if(counts[o.status]!=null)counts[o.status]++});const labels={novo:'Novos',preparando:'Preparando',pronto:'Prontos',em_entrega:'Em entrega',cancelado:'Cancelados'};$('statusList').innerHTML=Object.keys(labels).map(k=>`<div class="status-row"><span><i class="dot"></i>${labels[k]}</span><b>${counts[k]}</b></div>`).join('')}
function renderStock(){$('stockEmpty').hidden=!!stock.length;$('stockTable').innerHTML=stock.map(x=>`<tr><td><b>${esc(x.nome)}</b></td><td>${esc(x.categoria||'—')}</td><td class="${Number(x.saldo)<=Number(x.minimo)?'low':''}">${Number(x.saldo||0).toLocaleString('pt-BR')}</td><td>${Number(x.minimo||0)}</td><td>${esc(x.unidade||'un')}</td><td>${x.atualizado?new Date(x.atualizado).toLocaleDateString('pt-BR'):'—'}</td><td class="actions"><button data-edit="${x.id}">Editar</button><button data-move="${x.id}">Movimentar</button><button class="danger" data-del-stock="${x.id}">Excluir</button></td></tr>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>stockForm(stock.find(x=>x.id===b.dataset.edit)));document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveForm(b.dataset.move));document.querySelectorAll('[data-del-stock]').forEach(b=>b.onclick=()=>deleteStock(b.dataset.delStock))}
function renderMoves(){$('movementList').innerHTML=moves.slice().sort((a,b)=>b.em.localeCompare(a.em)).slice(0,8).map(m=>`<div class="movement"><span><b>${esc(m.nome)}</b> · ${esc(m.observacao||'')}</span><strong class="${m.tipo==='entrada'?'in':'out'}">${m.tipo==='entrada'?'+':'−'}${m.quantidade} ${esc(m.unidade||'')}</strong></div>`).join('')||'<p class="empty">Nenhuma movimentação registrada.</p>'}
function cashData(){const list=Array.isArray(cash?.movimentos)?cash.movimentos.filter(m=>inPeriod(new Date(m.em||0))):[];const sales=list.filter(m=>m.tipo==='venda').reduce((s,m)=>s+(amount(m.valor)||0),0),supplies=list.filter(m=>m.tipo==='suprimento').reduce((s,m)=>s+(amount(m.valor)||0),0),withdrawals=list.filter(m=>m.tipo==='sangria').reduce((s,m)=>s+(amount(m.valor)||0),0);return {list,sales,supplies,withdrawals,net:sales+supplies-withdrawals,available:!!cash&&list.length>0}}
function renderExpenses(){const list=expenses.filter(e=>inPeriod(new Date(e.vencimento+'T12:00:00'))), total=list.reduce((s,e)=>s+(amount(e.valor)||0),0), done=validOrders().filter(delivered), rev=orderRevenue(done), revenueAvailable=done.some(o=>amount(o.total)!==null), expenseAvailable=list.some(e=>amount(e.valor)!==null), cd=cashData();$('fReceita').textContent=shown(rev,revenueAvailable);$('fDespesas').textContent=shown(total,expenseAvailable);$('fResultado').textContent=shown(rev-total,revenueAvailable&&expenseAvailable);$('fCaixa').textContent=shown(cd.net,cd.available);$('fCaixaDetalhe').textContent=cd.available?`vendas ${money(cd.sales)} · suprimentos ${money(cd.supplies)} · sangrias ${money(cd.withdrawals)}`:'nenhum movimento registrado no período';$('financeNote').innerHTML='<b>Leitura segura:</b> receita e despesas são registros do período selecionado. Movimentos de caixa vêm apenas do caixa atual; saldo, contas a receber, taxas e custos não registrados não são estimados.';$('expenseEmpty').hidden=!!list.length;$('expenseTable').innerHTML=list.slice().sort((a,b)=>b.vencimento.localeCompare(a.vencimento)).map(e=>`<tr><td><b>${esc(e.descricao)}</b></td><td>${esc(e.categoria)}</td><td>${new Date(e.vencimento+'T12:00:00').toLocaleDateString('pt-BR')}</td><td>${money(e.valor)}</td><td>${e.paga?'✅ Paga':'⏳ Pendente'}</td><td class="actions"><button data-toggle-exp="${e.id}">${e.paga?'Reabrir':'Marcar paga'}</button><button class="danger" data-del-exp="${e.id}">Excluir</button></td></tr>`).join('');document.querySelectorAll('[data-toggle-exp]').forEach(b=>b.onclick=async()=>{const e=expenses.find(x=>x.id===b.dataset.toggleExp);e.paga=!e.paga;await save('expenses',expenses)});document.querySelectorAll('[data-del-exp]').forEach(b=>b.onclick=()=>deleteExpense(b.dataset.delExp))}
function timelineEvents(order){const raw=Array.isArray(order&&order.timeline)?order.timeline:Object.values((order&&order.timeline)||{});return raw.filter(ev=>ev&&typeof ev==='object').map(ev=>{const value=ev.em??ev.createdAt??ev.timestamp;let time=NaN;if(value&&typeof value==='object'&&Number.isFinite(Number(value.seconds)))time=Number(value.seconds)*1000;else if(value!=null)time=new Date(value).getTime();const rawStatus=String(ev.status||ev.evento||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[-\s]/g,'_');const status=rawStatus.replace(/^pedido_/,'').replace(/^status_/,'').replace(/^alterado_?/,'');return {status,time}}).filter(ev=>Number.isFinite(ev.time)).sort((a,b)=>a.time-b.time)}
function durationFor(order,startStatus,endStatus){const events=timelineEvents(order),start=events.find(ev=>ev.status===startStatus);if(!start)return null;const end=events.find(ev=>ev.status===endStatus&&ev.time>start.time);if(!end)return null;const minutes=(end.time-start.time)/60000;return Number.isFinite(minutes)&&minutes>0?minutes:null}
function averageDuration(list,startStatus,endStatus){const values=list.map(o=>durationFor(o,startStatus,endStatus)).filter(v=>v!==null);return values.length?values.reduce((sum,v)=>sum+v,0)/values.length:null}
function formatDuration(minutes){if(minutes===null)return 'Sem dados';if(minutes<1)return '<1 min';return `${Math.round(minutes)} min`}
function renderReports(os,done,rev){const filtered=os.filter(o=>(reportStatus==='all'||String(o.status||'')===reportStatus)&&(reportChannel==='all'||String(o.canal||o.origem||'outro')===reportChannel));const filteredDone=filtered.filter(delivered), revenue=orderRevenue(filteredDone), revenueAvailable=filteredDone.some(o=>amount(o.total)!==null),products={},channels={};filteredDone.forEach(o=>{const channel=String(o.canal||o.origem||'outro');(o.itens||[]).forEach(i=>{const n=i.nome||i.name||'Item sem nome';{const q=amount(i.quantidade??i.qtd??1);if(q!==null&&q>0)products[n]=(products[n]||0)+q}});{const n=amount(o.total);if(n!==null)channels[channel]=(channels[channel]||0)+n}});rank('productReport',products,true);rank('channelReport',channels,false);$('rReceita').textContent=shown(revenue,revenueAvailable);$('rPedidos').textContent=filtered.length;$('rTicket').textContent=shown(revenue/filteredDone.length,revenueAvailable&&filteredDone.length>0);$('rCancelados').textContent=filtered.filter(o=>String(o.status||'').toLowerCase()==='cancelado').length;$('rPrep').textContent=formatDuration(averageDuration(filtered,'preparando','pronto'));$('rDelivery').textContent=formatDuration(averageDuration(filtered,'em_entrega','entregue'));$('reportSummary').innerHTML=`<div><span>Pedidos analisados</span><b>${filtered.length}</b></div><div><span>Entregues</span><b>${filteredDone.length}</b></div><div><span>Conversão em entrega</span><b>${filtered.length?Math.round(filteredDone.length/filtered.length*100):0}%</b></div>`}
function renderReportFilters(os){const channels=[...new Set(os.map(o=>String(o.canal||o.origem||'outro')))];const statuses=[...new Set(os.map(o=>String(o.status||'sem status')))];$('reportChannel').innerHTML='<option value="all">Todos os canais</option>'+channels.map(x=>`<option value="${esc(x)}" ${x===reportChannel?'selected':''}>${esc(x)}</option>`).join('');$('reportStatus').innerHTML='<option value="all">Todos os status</option>'+statuses.map(x=>`<option value="${esc(x)}" ${x===reportStatus?'selected':''}>${esc(x)}</option>`).join('')}
function reservationDate(r){return new Date(`${r.data}T${r.hora||'00:00'}`)}
function reservationConflict(candidate){if(['cancelada','cancelado'].includes(String(candidate.status).toLowerCase()))return false;const start=reservationDate(candidate).getTime(), end=start+90*60000;return reservations.some(r=>String(r.id)!==String(candidate.id)&&String(r.mesa).trim()===String(candidate.mesa).trim()&&!['cancelada','cancelado'].includes(String(r.status||'').toLowerCase())&&r.data===candidate.data&&reservationDate(r).getTime()<end&&reservationDate(r).getTime()+90*60000>start)}
function renderReservations(){$('reservationEmpty').hidden=!!reservations.length;$('reservationTable').innerHTML=reservations.slice().sort((a,b)=>reservationDate(a)-reservationDate(b)).map(r=>`<tr><td><b>${new Date(`${r.data}T12:00:00`).toLocaleDateString('pt-BR')}</b> às ${esc(r.hora)}</td><td>${esc(r.cliente)}</td><td>Mesa ${esc(r.mesa)}</td><td>${esc(r.pessoas)}</td><td><span class="badge status-${esc(r.status)}">${esc(r.status)}</span></td><td class="actions"><button data-edit-res="${esc(r.id)}">Editar</button><button class="danger" data-del-res="${esc(r.id)}">Excluir</button></td></tr>`).join('');document.querySelectorAll('[data-edit-res]').forEach(b=>b.onclick=()=>reservationForm(reservations.find(r=>String(r.id)===b.dataset.editRes)));document.querySelectorAll('[data-del-res]').forEach(b=>b.onclick=()=>deleteReservation(b.dataset.delRes))}
function reservationForm(item){const today=new Date().toISOString().slice(0,10);modal(item?'Editar reserva':'Nova reserva',`<div class="form-grid"><label>Cliente<input name="cliente" required value="${esc(item?.cliente||'')}"></label><label>Data<input name="data" type="date" required value="${esc(item?.data||today)}"></label><label>Horário<input name="hora" type="time" required value="${esc(item?.hora||'19:00')}"></label><label>Mesa<input name="mesa" required inputmode="numeric" value="${esc(item?.mesa||'')}"></label><label>Pessoas<input name="pessoas" type="number" min="1" required value="${esc(item?.pessoas||2)}"></label><label>Status<select name="status"><option value="pendente" ${!item||item.status==='pendente'?'selected':''}>Pendente</option><option value="confirmada" ${item?.status==='confirmada'?'selected':''}>Confirmada</option><option value="chegou" ${item?.status==='chegou'?'selected':''}>Chegou</option><option value="concluida" ${item?.status==='concluida'?'selected':''}>Concluída</option><option value="cancelada" ${item?.status==='cancelada'?'selected':''}>Cancelada</option></select></label><div class="form-actions"><button type="button" class="secondary" id="cancelForm">Cancelar</button><button class="primary">Salvar reserva</button></div></div>`,async f=>{const r={id:item?.id||'res_'+Date.now(),cliente:String(f.get('cliente')).trim(),data:f.get('data'),hora:f.get('hora'),mesa:String(f.get('mesa')).trim(),pessoas:Number(f.get('pessoas')),status:f.get('status'),atualizadaEm:new Date().toISOString()};if(reservationConflict(r)){toast('Conflito: esta mesa já tem reserva neste horário.');return false}if(item)reservations=reservations.map(x=>String(x.id)===String(item.id)?r:x);else reservations.push(r);await save('reservations',reservations);toast('Reserva salva')})}
async function deleteReservation(id){if(!confirm('Excluir esta reserva?'))return;reservations=reservations.filter(r=>String(r.id)!==String(id));await save('reservations',reservations);toast('Reserva excluída')}
function rank(id,obj,qty){const vals=Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,8),max=vals[0]?.[1]||1;$(id).innerHTML=vals.map((x,i)=>`<div class="rank"><b>${i+1}</b><span>${esc(x[0])}</span><strong>${qty?x[1]:money(x[1])}</strong><div class="track"><i style="width:${x[1]/max*100}%"></i></div></div>`).join('')||'<p class="empty">Sem dados no período.</p>'}
function modal(title,html,onSubmit){$('modalTitle').textContent=title;$('modalForm').innerHTML=html;$('modal').hidden=false;const cancel=$('cancelForm');if(cancel)cancel.onclick=()=>{$('modal').hidden=true};$('modalForm').onsubmit=async e=>{e.preventDefault();const result=await onSubmit(new FormData(e.target));if(result!==false)$('modal').hidden=true};$('closeModal').onclick=()=>{$('modal').hidden=true}}
function stockForm(item){modal(item?'Editar item':'Novo item',`<div class="form-grid"><label>Nome<input name="nome" required value="${esc(item?.nome||'')}"></label><label>Categoria<input name="categoria" value="${esc(item?.categoria||'Insumos')}"></label><label>Saldo atual<input name="saldo" type="number" min="0" step="0.01" required value="${item?.saldo||0}"></label><label>Estoque mínimo<input name="minimo" type="number" min="0" step="0.01" value="${item?.minimo||0}"></label><label>Custo unitário<input name="custoUnitario" type="number" min="0" step="0.0001" value="${item?.custoUnitario||0}"></label><label>Unidade<select name="unidade"><option ${item?.unidade==='kg'?'selected':''}>kg</option><option ${item?.unidade==='l'?'selected':''}>l</option><option ${!item||item?.unidade==='un'?'selected':''}>un</option></select></label><div class="form-actions"><button type="button" class="secondary" id="cancelForm">Cancelar</button><button class="primary">Salvar item</button></div></div>`,async f=>{const x={id:item?.id||'stk_'+Date.now(),nome:f.get('nome'),categoria:f.get('categoria'),saldo:Number(f.get('saldo')),minimo:Number(f.get('minimo')),unidade:f.get('unidade'),custoUnitario:Number(f.get('custoUnitario')||0),atualizado:new Date().toISOString()};if(item)stock=stock.map(s=>s.id===item.id?x:s);else stock.push(x);await save('stock',stock)});}
function moveForm(id){const x=stock.find(s=>s.id===id);modal('Movimentar '+x.nome,`<div class="form-grid"><label>Tipo<select name="tipo"><option value="entrada">Entrada</option><option value="saida">Saída</option></select></label><label>Quantidade<input name="quantidade" type="number" min="0.01" step="0.01" required></label><label>Observação<input name="observacao" placeholder="Ex.: compra, perda, produção"></label><div class="form-actions"><button class="primary">Registrar</button></div></div>`,async f=>{const q=Number(f.get('quantidade'));if(f.get('tipo')==='saida'&&q>x.saldo){alert('A saída não pode ser maior que o saldo atual.');return false}x.saldo+=f.get('tipo')==='entrada'?q:-q;x.atualizado=new Date().toISOString();moves.push({id:'mov_'+Date.now(),stockId:id,nome:x.nome,unidade:x.unidade,tipo:f.get('tipo'),quantidade:q,observacao:f.get('observacao'),em:new Date().toISOString()});await save('stock',stock);await save('moves',moves)})}
async function deleteStock(id){if(!confirm('Excluir este item e manter o histórico de movimentos?'))return;stock=stock.filter(x=>x.id!==id);await save('stock',stock);toast('Item excluído')}
function expenseForm(){modal('Nova despesa',`<div class="form-grid"><label>Descrição<input name="descricao" required placeholder="Ex.: compra de mussarela"></label><label>Categoria<select name="categoria"><option>Insumos</option><option>Aluguel</option><option>Equipe</option><option>Contas</option><option>Marketing</option><option>Outros</option></select></label><label>Vencimento<input name="vencimento" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Valor<input name="valor" type="number" min="0.01" step="0.01" required></label><label><input name="paga" type="checkbox"> Já paga</label><div class="form-actions"><button class="primary">Salvar despesa</button></div></div>`,async f=>{expenses.push({id:'exp_'+Date.now(),descricao:f.get('descricao'),categoria:f.get('categoria'),vencimento:f.get('vencimento'),valor:Number(f.get('valor')),paga:f.get('paga')==='on',criadaEm:new Date().toISOString()});await save('expenses',expenses)})}
async function deleteExpense(id){if(!confirm('Excluir esta despesa?'))return;expenses=expenses.filter(e=>e.id!==id);await save('expenses',expenses);toast('Despesa excluída')}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function exportCSV(){const rows=[['Data','Status','Canal','Total'],...validOrders().filter(o=>(reportStatus==='all'||String(o.status||'')===reportStatus)&&(reportChannel==='all'||String(o.canal||o.origem||'outro')===reportChannel)).map(o=>[dateOf(o).toISOString(),o.status,o.canal||o.origem||'',Number(o.total||0).toFixed(2)])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n')],{type:'text/csv'}));a.download='relatorio-nonna.csv';a.click();URL.revokeObjectURL(a.href)}
function init(){ $('dataAtual').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'});document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});$('periodo').onchange=e=>{period=e.target.value;renderAll()};$('reportChannel').onchange=e=>{reportChannel=e.target.value;renderAll()};$('reportStatus').onchange=e=>{reportStatus=e.target.value;renderAll()};$('refresh').onclick=sync;$('newStock').onclick=()=>stockForm();$('newExpense').onclick=expenseForm;$('newReservation').onclick=()=>reservationForm();$('exportReport').onclick=exportCSV;sync();if(window.DB){DB.onChange(()=>sync())}}
function wait(){if(window.DB&&DB.getPedidos&&DB._ready){init()}else setTimeout(wait,80)} wait();
})();
