/* NONNA Gestão: pedidos vêm do DB existente; estoque e despesas usam Firebase
   nos ambientes configurados e localStorage como fallback isolado deste módulo. */
(function(){'use strict';
const $=id=>document.getElementById(id), money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEYS={stock:'nonna_gestao_estoque',moves:'nonna_gestao_movimentos',expenses:'nonna_gestao_despesas',reservations:'nonna_gestao_reservas',closings:'nonna_gestao_fechamentos',users:'nonna_gestao_usuarios'}; let stock=[],moves=[],expenses=[],reservations=[],orders=[],cash=null,closings=[],users=[],settings={},menu={},dayClosings=[],period='30', remote=false, reportChannel='all', reportStatus='all', currentStaff=null;
const ALLOWED_ROLES=['owner','manager','cashier','kitchen','waiter','courier'];
const read=k=>{try{return JSON.parse(localStorage.getItem(KEYS[k])||'[]')}catch(e){return[]}}, write=(k,v)=>localStorage.setItem(KEYS[k],JSON.stringify(v));
const amount=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null}, shown=(v,available)=>available?money(v):'Sem dados';
function dateOf(o){return new Date(o.criadoEm||o.createdAt||o.data||0)} function inPeriod(d){if(!(d instanceof Date)||!Number.isFinite(d.getTime()))return false;if(period==='all')return true;const days=period==='today'?1:Number(period), start=new Date();start.setHours(0,0,0,0);if(days>1)start.setDate(start.getDate()-days+1);return d>=start}
function validOrders(){return orders.filter(o=>inPeriod(dateOf(o)))} function delivered(o){return ['entregue','concluido','finalizado'].includes(String(o.status||'').toLowerCase())}
function orderRevenue(list){return list.reduce((x,o)=>{const n=amount(o.total);return n===null?x:x+n},0)}
function loadLocal(){stock=read('stock');moves=read('moves');expenses=read('expenses');reservations=read('reservations');cash=DB&&DB.getCaixaAtual?DB.getCaixaAtual():null;try{closings=JSON.parse(localStorage.getItem('donna_caixa_historico')||'[]')}catch(_){closings=read('closings')}if(cash&&cash.status==='fechado'&&!closings.some(x=>String(x.id)===String(cash.id)))closings.push(cash);users=read('users');try{settings=JSON.parse(localStorage.getItem('donna_config')||'{}')}catch(e){settings={}}}
async function sync(){const conn=$('connection');if(conn)conn.textContent='● carregando';orders=(window.DB&&DB.getPedidos)?(DB.getPedidos()||[]):[];cash=window.DB&&DB.getCaixaAtual?DB.getCaixaAtual():null;if(window.firebase&&DB&&DB.backend==='firebase'){remote=true;try{const [s,m,e,r,c,h,u,cf,mc,dc]=await Promise.all(['estoque','movimentacoes','despesas','reservas'].map(p=>firebase.database().ref('gestao/'+p).once('value')).concat(firebase.database().ref('caixa/atual').once('value'),firebase.database().ref('caixa/historico').once('value'),(firebase.auth&&firebase.auth().currentUser?firebase.database().ref('userProfiles/'+firebase.auth().currentUser.uid).once('value'):Promise.resolve(null)),firebase.database().ref('config').once('value'),firebase.database().ref('cardapio').once('value'),firebase.database().ref('gestao/diasEncerrados').once('value')));stock=Object.values(s.val()||{});moves=Object.values(m.val()||{});expenses=Object.values(e.val()||{});reservations=Object.values(r.val()||{});cash=c.val()||null;closings=Object.values(h.val()||{});currentStaff=u?.val()?{...u.val(),uid:firebase.auth().currentUser.uid,email:firebase.auth().currentUser.email}:null; if(currentStaff?.restaurantId){const us=await firebase.database().ref('userProfiles').orderByChild('restaurantId').equalTo(String(currentStaff.restaurantId)).once('value');users=Object.values(us.val()||{});}else users=[]; settings=cf.val()||{};menu=mc.val()||{};dayClosings=Object.values(dc.val()||{});}catch(err){loadLocal();remote=false;menu=window.DB?.getCardapio?.()||{};if(conn){conn.textContent='● erro · dados locais';conn.title='Não foi possível sincronizar; exibindo o último estado local.';}toast('Não foi possível sincronizar. Confira sua conexão.')} }else { loadLocal(); menu=window.DB?.getCardapio?.()||{}; }if(conn&&!conn.textContent.includes('erro'))conn.textContent=remote?'● sincronizado':'● modo local';renderAll()}
async function save(kind,arr){const path={stock:'estoque',movements:'movimentacoes',moves:'movimentacoes',expenses:'despesas',reservations:'reservas'}[kind];if(remote){const obj={};arr.forEach(x=>obj[x.id]=x);await firebase.database().ref('gestao/'+path).set(obj);if(kind==='expenses' && window.DBRemote?.registrarFinanceiro){const ultimo=arr[arr.length-1];if(ultimo)try{await DBRemote.registrarFinanceiro({tipo:'despesa',origem:'gestao',valor:Number(ultimo.valor||0),categoria:ultimo.categoria,descricao:ultimo.descricao,referencia:ultimo.id,status:ultimo.paga?'pago':'pendente'})}catch(e){console.warn('[NONNA] financeiro',e.message)} } }else write(kind,arr);renderAll()}
function renderAll(){const os=validOrders(), done=os.filter(delivered), revenue=orderRevenue(done), revenueAvailable=done.some(o=>amount(o.total)!==null);$('mVendas').textContent=shown(revenue,revenueAvailable);$('mPedidos').textContent=os.length+' pedidos no período';$('mConcluidos').textContent=done.length;$('mTicket').textContent=shown(revenue/done.length,revenueAvailable&&done.length>0);const low=stock.filter(x=>Number(x.saldo||0)<=Number(x.minimo||0));$('mEstoque').textContent=stock.reduce((s,x)=>s+Number(x.saldo||0),0);$('mBaixo').textContent=low.length?low.length+' item(ns) abaixo do mínimo':'Nenhum alerta';renderChart(os);renderStatuses(os);renderMenu();renderStock();renderMoves();renderExpenses();renderDailyFinance();renderReservations();renderUsers();renderSettings();renderReportFilters(os);renderReports(os,done,revenue)}
function renderChart(os){const days=period==='today'?1:period==='all'?14:Number(period);const arr=[];for(let i=days-1;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);arr.push({d,n:os.filter(o=>delivered(o)&&dateOf(o).toDateString()===d.toDateString()).reduce((s,o)=>s+(amount(o.total)||0),0)})}const max=Math.max(...arr.map(x=>x.n),1);$('salesChart').innerHTML=arr.map(x=>`<div class="bar" style="height:${Math.max(4,x.n/max*175)}px" title="${money(x.n)}"><em>${x.n?money(x.n):''}</em><small>${x.d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</small></div>`).join('')}
function renderStatuses(os){const counts={novo:0,preparando:0,pronto:0,em_entrega:0,cancelado:0};os.forEach(o=>{if(counts[o.status]!=null)counts[o.status]++});const labels={novo:'Novos',preparando:'Preparando',pronto:'Prontos',em_entrega:'Em entrega',cancelado:'Cancelados'};$('statusList').innerHTML=Object.keys(labels).map(k=>`<div class="status-row"><span><i class="dot"></i>${labels[k]}</span><b>${counts[k]}</b></div>`).join('')}
function menuItems(){return Object.entries(menu||{}).filter(([k,v])=>Array.isArray(v)).flatMap(([categoria,arr])=>arr.map((x,i)=>({...x,_categoria:categoria,_index:i,_id:String(x.id||categoria+'_'+i)})));}
function renderMenu(){const items=menuItems();$('menuEmpty').hidden=!!items.length;$('menuTable').innerHTML=items.map(x=>`<tr><td><b>${esc(x.emoji||'🍕')} ${esc(x.nome||x.name||'Item')}</b>${x.foto||x.imagem?`<br><img class="menu-thumb" src="${esc(x.foto||x.imagem)}" alt="">`:''}</td><td>${esc(x._categoria)}</td><td>${amount(x.preco??x.price)!==null?money(x.preco??x.price):'Sem preço'}</td><td>${x.ativo===false?'Inativo':'Ativo'}</td><td class="actions"><button data-edit-menu="${esc(x._id)}">Editar</button><button class="danger" data-toggle-menu="${esc(x._id)}">${x.ativo===false?'Ativar':'Desativar'}</button></td></tr>`).join('');document.querySelectorAll('[data-edit-menu]').forEach(b=>b.onclick=()=>menuForm(items.find(x=>x._id===b.dataset.editMenu)));document.querySelectorAll('[data-toggle-menu]').forEach(b=>b.onclick=()=>toggleMenu(items.find(x=>x._id===b.dataset.toggleMenu)));}
async function saveMenu(){if(remote)await firebase.database().ref('cardapio').set(menu);else {localStorage.setItem('donna_cardapio',JSON.stringify(menu));}renderAll();}
function menuForm(item){const cats=Object.keys(menu).filter(k=>Array.isArray(menu[k]));modal(item?'Editar item':'Novo item',`<div class="form-grid"><label>Nome<input name="nome" maxlength="100" required value="${esc(item?.nome||item?.name||'')}"></label><label>Categoria<select name="categoria">${(cats.length?cats:['sabores']).map(c=>`<option value="${esc(c)}" ${c===(item?._categoria||'sabores')?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Preço<input name="preco" type="number" min="0" step="0.01" required value="${item?.preco??item?.price??''}"></label><label>Emoji<input name="emoji" maxlength="8" value="${esc(item?.emoji||'🍕')}"></label><label>Foto (URL segura)<input name="foto" type="url" maxlength="500" placeholder="https://..." value="${esc(item?.foto||item?.imagem||'')}"><small>Use uma URL HTTPS; não envie dados sensíveis.</small></label><div class="form-actions"><button type="button" class="secondary" id="cancelForm">Cancelar</button><button class="primary">Salvar item</button></div></div>`,async f=>{const cat=String(f.get('categoria')), arr=Array.isArray(menu[cat])?menu[cat].slice():[], itemId=item?._id||('item_'+Date.now());const updated={...(item||{}),id:item?.id||itemId,nome:String(f.get('nome')).trim(),preco:Number(f.get('preco')),emoji:String(f.get('emoji')||'🍕').slice(0,8),foto:String(f.get('foto')||'').trim(),ativo:item?.ativo!==false};if(item&&item._categoria!==cat){menu[item._categoria]=menu[item._categoria].filter((x,i)=>String(x.id||item._categoria+'_'+i)!==item._id);arr.push(updated)}else {const ix=arr.findIndex((x,i)=>String(x.id||cat+'_'+i)===itemId);if(ix>=0)arr[ix]=updated;else arr.push(updated)}menu[cat]=arr;await saveMenu();toast('Item salvo')})}
function toggleMenu(item){if(!item)return;item.ativo=item.ativo===false;menu[item._categoria]=menu[item._categoria].map((x,i)=>String(x.id||item._categoria+'_'+i)===item._id?{...x,ativo:item.ativo}:x);saveMenu().then(()=>toast(item.ativo?'Item ativado':'Item desativado')).catch(()=>toast('Não foi possível salvar'));}
function renderStock(){$('stockEmpty').hidden=!!stock.length;$('stockTable').innerHTML=stock.map(x=>`<tr><td><b>${esc(x.nome)}</b></td><td>${esc(x.categoria||'—')}</td><td class="${Number(x.saldo)<=Number(x.minimo)?'low':''}">${Number(x.saldo||0).toLocaleString('pt-BR')}</td><td>${Number(x.minimo||0)}</td><td>${esc(x.unidade||'un')}</td><td>${x.atualizado?new Date(x.atualizado).toLocaleDateString('pt-BR'):'—'}</td><td class="actions"><button data-edit="${x.id}">Editar</button><button data-move="${x.id}">Movimentar</button><button class="danger" data-del-stock="${x.id}">Excluir</button></td></tr>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>stockForm(stock.find(x=>x.id===b.dataset.edit)));document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveForm(b.dataset.move));document.querySelectorAll('[data-del-stock]').forEach(b=>b.onclick=()=>deleteStock(b.dataset.delStock))}
function renderMoves(){$('movementList').innerHTML=moves.slice().sort((a,b)=>b.em.localeCompare(a.em)).slice(0,8).map(m=>`<div class="movement"><span><b>${esc(m.nome)}</b> · ${esc(m.observacao||'')}</span><strong class="${m.tipo==='entrada'?'in':'out'}">${m.tipo==='entrada'?'+':'−'}${m.quantidade} ${esc(m.unidade||'')}</strong></div>`).join('')||'<p class="empty">Nenhuma movimentação registrada.</p>'}
function cashData(){const list=Array.isArray(cash?.movimentos)?cash.movimentos.filter(m=>inPeriod(new Date(m.em||0))):[];const sales=list.filter(m=>m.tipo==='venda').reduce((s,m)=>s+(amount(m.valor)||0),0),supplies=list.filter(m=>m.tipo==='suprimento').reduce((s,m)=>s+(amount(m.valor)||0),0),withdrawals=list.filter(m=>m.tipo==='sangria').reduce((s,m)=>s+(amount(m.valor)||0),0);return {list,sales,supplies,withdrawals,net:sales+supplies-withdrawals,available:!!cash&&list.length>0}}
function renderExpenses(){const list=expenses.filter(e=>inPeriod(new Date(e.vencimento+'T12:00:00'))), total=list.reduce((s,e)=>s+(amount(e.valor)||0),0), done=validOrders().filter(delivered), rev=orderRevenue(done), revenueAvailable=done.some(o=>amount(o.total)!==null), expenseAvailable=list.some(e=>amount(e.valor)!==null), cd=cashData();$('fReceita').textContent=shown(rev,revenueAvailable);$('fDespesas').textContent=shown(total,expenseAvailable);$('fResultado').textContent=shown(rev-total,revenueAvailable&&expenseAvailable);$('fCaixa').textContent=shown(cd.net,cd.available);$('fCaixaDetalhe').textContent=cd.available?`vendas ${money(cd.sales)} · suprimentos ${money(cd.supplies)} · sangrias ${money(cd.withdrawals)}`:'nenhum movimento registrado no período';$('financeNote').innerHTML='<b>Leitura segura:</b> receita e despesas são registros do período selecionado. Movimentos de caixa vêm apenas do caixa atual; saldo, contas a receber, taxas e custos não registrados não são estimados.';$('expenseEmpty').hidden=!!list.length;$('expenseTable').innerHTML=list.slice().sort((a,b)=>b.vencimento.localeCompare(a.vencimento)).map(e=>`<tr><td><b>${esc(e.descricao)}</b></td><td>${esc(e.categoria)}</td><td>${new Date(e.vencimento+'T12:00:00').toLocaleDateString('pt-BR')}</td><td>${money(e.valor)}</td><td>${e.paga?'✅ Paga':'⏳ Pendente'}</td><td class="actions"><button data-toggle-exp="${e.id}">${e.paga?'Reabrir':'Marcar paga'}</button><button class="danger" data-del-exp="${e.id}">Excluir</button></td></tr>`).join('');document.querySelectorAll('[data-toggle-exp]').forEach(b=>b.onclick=async()=>{const e=expenses.find(x=>x.id===b.dataset.toggleExp);e.paga=!e.paga;await save('expenses',expenses)});document.querySelectorAll('[data-del-exp]').forEach(b=>b.onclick=()=>deleteExpense(b.dataset.delExp))}
function timelineEvents(order){const raw=Array.isArray(order&&order.timeline)?order.timeline:Object.values((order&&order.timeline)||{});return raw.filter(ev=>ev&&typeof ev==='object').map(ev=>{const value=ev.em??ev.createdAt??ev.timestamp;let time=NaN;if(value&&typeof value==='object'&&Number.isFinite(Number(value.seconds)))time=Number(value.seconds)*1000;else if(value!=null)time=new Date(value).getTime();const rawStatus=String(ev.status||ev.evento||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[-\s]/g,'_');const status=rawStatus.replace(/^pedido_/,'').replace(/^status_/,'').replace(/^alterado_?/,'');return {status,time}}).filter(ev=>Number.isFinite(ev.time)).sort((a,b)=>a.time-b.time)}
function durationFor(order,startStatus,endStatus){const events=timelineEvents(order),start=events.find(ev=>ev.status===startStatus);if(!start)return null;const end=events.find(ev=>ev.status===endStatus&&ev.time>start.time);if(!end)return null;const minutes=(end.time-start.time)/60000;return Number.isFinite(minutes)&&minutes>0?minutes:null}
function averageDuration(list,startStatus,endStatus){const values=list.map(o=>durationFor(o,startStatus,endStatus)).filter(v=>v!==null);return values.length?values.reduce((sum,v)=>sum+v,0)/values.length:null}
function formatDuration(minutes){if(minutes===null)return 'Sem dados';if(minutes<1)return '<1 min';return `${Math.round(minutes)} min`}
function renderReports(os,done,rev){const filtered=os.filter(o=>(reportStatus==='all'||String(o.status||'')===reportStatus)&&(reportChannel==='all'||String(o.canal||o.origem||'outro')===reportChannel));const filteredDone=filtered.filter(delivered), revenue=orderRevenue(filteredDone), revenueAvailable=filteredDone.some(o=>amount(o.total)!==null),products={},channels={};filteredDone.forEach(o=>{const channel=String(o.canal||o.origem||'outro');(o.itens||[]).forEach(i=>{const n=i.nome||i.name||'Item sem nome';{const q=amount(i.quantidade??i.qtd??1);if(q!==null&&q>0)products[n]=(products[n]||0)+q}});{const n=amount(o.total);if(n!==null)channels[channel]=(channels[channel]||0)+n}});rank('productReport',products,true);rank('channelReport',channels,false);$('rReceita').textContent=shown(revenue,revenueAvailable);$('rPedidos').textContent=filtered.length;$('rTicket').textContent=shown(revenue/filteredDone.length,revenueAvailable&&filteredDone.length>0);$('rCancelados').textContent=filtered.filter(o=>String(o.status||'').toLowerCase()==='cancelado').length;$('rPrep').textContent=formatDuration(averageDuration(filtered,'preparando','pronto'));$('rDelivery').textContent=formatDuration(averageDuration(filtered,'em_entrega','entregue'));$('reportSummary').innerHTML=`<div><span>Pedidos analisados</span><b>${filtered.length}</b></div><div><span>Entregues</span><b>${filteredDone.length}</b></div><div><span>Conversão em entrega</span><b>${filtered.length?Math.round(filteredDone.length/filtered.length*100):0}%</b></div>`}
function renderReportFilters(os){const channels=[...new Set(os.map(o=>String(o.canal||o.origem||'outro')))];const statuses=[...new Set(os.map(o=>String(o.status||'sem status')))];$('reportChannel').innerHTML='<option value="all">Todos os canais</option>'+channels.map(x=>`<option value="${esc(x)}" ${x===reportChannel?'selected':''}>${esc(x)}</option>`).join('');$('reportStatus').innerHTML='<option value="all">Todos os status</option>'+statuses.map(x=>`<option value="${esc(x)}" ${x===reportStatus?'selected':''}>${esc(x)}</option>`).join('')}
function reservationDate(r){return new Date(`${r.data}T${r.hora||'00:00'}`)}
function reservationConflict(candidate){if(['cancelada','cancelado'].includes(String(candidate.status).toLowerCase()))return false;const start=reservationDate(candidate).getTime(), end=start+90*60000;return reservations.some(r=>String(r.id)!==String(candidate.id)&&String(r.mesa).trim()===String(candidate.mesa).trim()&&!['cancelada','cancelado'].includes(String(r.status||'').toLowerCase())&&r.data===candidate.data&&reservationDate(r).getTime()<end&&reservationDate(r).getTime()+90*60000>start)}
function renderReservations(){$('reservationEmpty').hidden=!!reservations.length;$('reservationTable').innerHTML=reservations.slice().sort((a,b)=>reservationDate(a)-reservationDate(b)).map(r=>`<tr><td><b>${new Date(`${r.data}T12:00:00`).toLocaleDateString('pt-BR')}</b> às ${esc(r.hora)}</td><td>${esc(r.cliente)}</td><td>Mesa ${esc(r.mesa)}</td><td>${esc(r.pessoas)}</td><td><span class="badge status-${esc(r.status)}">${esc(r.status)}</span></td><td class="actions"><button data-edit-res="${esc(r.id)}">Editar</button><button class="danger" data-del-res="${esc(r.id)}">Excluir</button></td></tr>`).join('');document.querySelectorAll('[data-edit-res]').forEach(b=>b.onclick=()=>reservationForm(reservations.find(r=>String(r.id)===b.dataset.editRes)));document.querySelectorAll('[data-del-res]').forEach(b=>b.onclick=()=>deleteReservation(b.dataset.delRes))}
function reservationForm(item){const today=new Date().toISOString().slice(0,10);modal(item?'Editar reserva':'Nova reserva',`<div class="form-grid"><label>Cliente<input name="cliente" required value="${esc(item?.cliente||'')}"></label><label>Data<input name="data" type="date" required value="${esc(item?.data||today)}"></label><label>Horário<input name="hora" type="time" required value="${esc(item?.hora||'19:00')}"></label><label>Mesa<input name="mesa" required inputmode="numeric" value="${esc(item?.mesa||'')}"></label><label>Pessoas<input name="pessoas" type="number" min="1" required value="${esc(item?.pessoas||2)}"></label><label>Status<select name="status"><option value="pendente" ${!item||item.status==='pendente'?'selected':''}>Pendente</option><option value="confirmada" ${item?.status==='confirmada'?'selected':''}>Confirmada</option><option value="chegou" ${item?.status==='chegou'?'selected':''}>Chegou</option><option value="concluida" ${item?.status==='concluida'?'selected':''}>Concluída</option><option value="cancelada" ${item?.status==='cancelada'?'selected':''}>Cancelada</option></select></label><div class="form-actions"><button type="button" class="secondary" id="cancelForm">Cancelar</button><button class="primary">Salvar reserva</button></div></div>`,async f=>{const r={id:item?.id||'res_'+Date.now(),cliente:String(f.get('cliente')).trim(),data:f.get('data'),hora:f.get('hora'),mesa:String(f.get('mesa')).trim(),pessoas:Number(f.get('pessoas')),status:f.get('status'),atualizadaEm:new Date().toISOString()};if(reservationConflict(r)){toast('Conflito: esta mesa já tem reserva neste horário.');return false}if(item)reservations=reservations.map(x=>String(x.id)===String(item.id)?r:x);else reservations.push(r);await save('reservations',reservations);toast('Reserva salva')})}
async function deleteReservation(id){if(!confirm('Excluir esta reserva?'))return;reservations=reservations.filter(r=>String(r.id)!==String(id));await save('reservations',reservations);toast('Reserva excluída')}
function rank(id,obj,qty){const vals=Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,8),max=vals[0]?.[1]||1;$(id).innerHTML=vals.map((x,i)=>`<div class="rank"><b>${i+1}</b><span>${esc(x[0])}</span><strong>${qty?x[1]:money(x[1])}</strong><div class="track"><i style="width:${x[1]/max*100}%"></i></div></div>`).join('')||'<p class="empty">Sem dados no período.</p>'}
function modal(title,html,onSubmit){$('modalTitle').textContent=title;$('modalForm').innerHTML=html;$('modal').hidden=false;const cancel=$('cancelForm');if(cancel)cancel.onclick=()=>{$('modal').hidden=true};$('modalForm').onsubmit=async e=>{e.preventDefault();const result=await onSubmit(new FormData(e.target));if(result!==false)$('modal').hidden=true};$('closeModal').onclick=()=>{$('modal').hidden=true}}
function stockForm(item){modal(item?'Editar item':'Novo item',`<div class="form-grid"><label>Nome<input name="nome" required value="${esc(item?.nome||'')}"></label><label>Categoria<input name="categoria" value="${esc(item?.categoria||'Insumos')}"></label><label>Saldo atual<input name="saldo" type="number" min="0" step="0.01" required value="${item?.saldo||0}"></label><label>Estoque mínimo<input name="minimo" type="number" min="0" step="0.01" value="${item?.minimo||0}"></label><label>Custo unitário<input name="custoUnitario" type="number" min="0" step="0.0001" value="${item?.custoUnitario||0}"></label><label>Unidade<select name="unidade"><option ${item?.unidade==='kg'?'selected':''}>kg</option><option ${item?.unidade==='l'?'selected':''}>l</option><option ${!item||item?.unidade==='un'?'selected':''}>un</option></select></label><div class="form-actions"><button type="button" class="secondary" id="cancelForm">Cancelar</button><button class="primary">Salvar item</button></div></div>`,async f=>{const x={id:item?.id||'stk_'+Date.now(),nome:f.get('nome'),categoria:f.get('categoria'),saldo:Number(f.get('saldo')),minimo:Number(f.get('minimo')),unidade:f.get('unidade'),custoUnitario:Number(f.get('custoUnitario')||0),atualizado:new Date().toISOString()};if(item)stock=stock.map(s=>s.id===item.id?x:s);else stock.push(x);await save('stock',stock)});}
function moveForm(id){const x=stock.find(s=>s.id===id);modal('Movimentar '+x.nome,`<div class="form-grid"><label>Tipo<select name="tipo"><option value="entrada">Entrada</option><option value="saida">Saída</option></select></label><label>Quantidade<input name="quantidade" type="number" min="0.01" step="0.01" required></label><label>Observação<input name="observacao" placeholder="Ex.: compra, perda, produção"></label><div class="form-actions"><button class="primary">Registrar</button></div></div>`,async f=>{const q=Number(f.get('quantidade'));if(f.get('tipo')==='saida'&&q>x.saldo){alert('A saída não pode ser maior que o saldo atual.');return false}x.saldo+=f.get('tipo')==='entrada'?q:-q;x.atualizado=new Date().toISOString();moves.push({id:'mov_'+Date.now(),stockId:id,nome:x.nome,unidade:x.unidade,tipo:f.get('tipo'),quantidade:q,observacao:f.get('observacao'),em:new Date().toISOString()});await save('stock',stock);await save('moves',moves)})}
async function deleteStock(id){if(!confirm('Excluir este item e manter o histórico de movimentos?'))return;stock=stock.filter(x=>x.id!==id);await save('stock',stock);toast('Item excluído')}
function expenseForm(){modal('Nova despesa',`<div class="form-grid"><label>Descrição<input name="descricao" required placeholder="Ex.: compra de mussarela"></label><label>Categoria<select name="categoria"><option>Insumos</option><option>Aluguel</option><option>Equipe</option><option>Contas</option><option>Marketing</option><option>Outros</option></select></label><label>Vencimento<input name="vencimento" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Valor<input name="valor" type="number" min="0.01" step="0.01" required></label><label><input name="paga" type="checkbox"> Já paga</label><div class="form-actions"><button class="primary">Salvar despesa</button></div></div>`,async f=>{expenses.push({id:'exp_'+Date.now(),descricao:f.get('descricao'),categoria:f.get('categoria'),vencimento:f.get('vencimento'),valor:Number(f.get('valor')),paga:f.get('paga')==='on',criadaEm:new Date().toISOString()});await save('expenses',expenses)})}
async function deleteExpense(id){if(!confirm('Excluir esta despesa?'))return;expenses=expenses.filter(e=>e.id!==id);await save('expenses',expenses);toast('Despesa excluída')}
function renderDailyFinance(){const os=validOrders().slice().sort((a,b)=>dateOf(b)-dateOf(a));$('dailyOrders').innerHTML=os.slice(0,20).map(o=>`<div class="movement"><span><b>#${esc(o.id||'')}</b> · ${esc(o.status||'')}</span><strong>${amount(o.total)!==null?money(o.total):'Sem total'}</strong></div>`).join('')||'<p class="empty">Nenhum pedido no período.</p>';const allClosings=[...closings,...dayClosings.map(c=>({...c,_day:true}))];$('closingList').innerHTML=allClosings.slice().sort((a,b)=>new Date(b.encerradoEm||b.fechadoEm||0)-new Date(a.encerradoEm||a.fechadoEm||0)).slice(0,12).map(c=>`<div class="movement"><span><b>${new Date(c.encerradoEm||c.fechadoEm||0).toLocaleDateString('pt-BR')}</b> · ${esc(c._day?'Encerramento do dia':(c.fechadoPor||c.operador||'Operador'))}</span><strong>${money(c._day?c.totalContado:c.valorContado||0)} <small>${c.diferenca!=null?'('+money(c.diferenca)+')':''}</small></strong></div>`).join('')||'<p class="empty">Nenhum fechamento registrado.</p>'}
function renderUsers(){const safe=users.filter(u=>u&&typeof u==='object');$('usersEmpty').hidden=!!safe.length;const canManage=!!currentStaff&&['owner','manager'].includes(currentStaff.role);$('usersTable').innerHTML=safe.map(u=>{const role=ALLOWED_ROLES.includes(u.role)?u.role:'sem função',id=String(u.id||u.uid||''),isSelf=id===String(currentStaff?.uid||''),isOwner=u.role==='owner';const roleOptions=ALLOWED_ROLES.filter(r=>currentStaff?.role==='manager'?r!=='owner':true);const last=u.lastAccessAt||u.ultimoAcesso;return `<tr><td><b>${esc(u.nome||u.displayName||'Usuário')}</b></td><td>${esc(u.email||'')}</td><td><select data-role-user="${esc(id)}" ${!canManage||isSelf||isOwner?'disabled':''}>${roleOptions.map(r=>`<option value="${r}" ${r===role?'selected':''}>${r}</option>`).join('')}</select></td><td>${esc(u.restaurantId||currentStaff?.restaurantId||'—')}</td><td>${last&&Number.isFinite(new Date(last).getTime())?new Date(last).toLocaleString('pt-BR'):'Nunca informado'}</td><td>${u.ativo===false?'Inativo':'Ativo'}</td><td class="actions">${canManage&&!isSelf&&!isOwner?`<button data-edit-user="${esc(id)}">Editar</button><button class="${u.ativo===false?'secondary':'danger'}" data-toggle-user="${esc(id)}">${u.ativo===false?'Ativar':'Desativar'}</button>`:''}</td></tr>`}).join('');document.querySelectorAll('[data-role-user]').forEach(sel=>sel.onchange=async()=>{const id=sel.dataset.roleUser,r=ALLOWED_ROLES.includes(sel.value)?sel.value:null;if(!r||!canManage)return;try{await firebase.database().ref('userProfiles/'+id).update({role:r});toast('Função atualizada');await sync()}catch(e){toast('Não foi possível atualizar a função')}});document.querySelectorAll('[data-edit-user]').forEach(b=>b.onclick=()=>editUserForm(safe.find(x=>String(x.id||x.uid)===b.dataset.editUser)));document.querySelectorAll('[data-toggle-user]').forEach(b=>b.onclick=()=>toggleUser(safe.find(x=>String(x.id||x.uid)===b.dataset.toggleUser)));}
function editUserForm(u){if(!u)return;modal('Editar usuário',`<div class="form-grid"><label>Nome<input name="nome" maxlength="80" required value="${esc(u.nome||'')}"></label><label>Função<select name="role">${ALLOWED_ROLES.filter(r=>currentStaff.role==='manager'?r!=='owner':true).map(r=>`<option value="${r}" ${r===u.role?'selected':''}>${r}</option>`).join('')}</select></label><div class="form-actions"><button class="primary">Salvar</button></div></div>`,async f=>{try{if(remote)await firebase.database().ref('userProfiles/'+u.uid).update({nome:String(f.get('nome')).trim(),role:f.get('role')});else {u.nome=String(f.get('nome')).trim();u.role=f.get('role');write('users',users)}await sync();toast('Usuário atualizado')}catch(e){toast('Não foi possível atualizar');return false}})}
function toggleUser(u){if(!u)return;if(u.ativo!==false&&!confirm('Desativar este usuário? O acesso será bloqueado, sem apagar a conta Auth.'))return;if(u.ativo===false&&!confirm('Reativar este usuário?'))return;const run=remote?firebase.database().ref('userProfiles/'+u.uid).update({ativo:u.ativo===false}):Promise.resolve((u.ativo=u.ativo===false,write('users',users)));run.then(()=>{toast(u.ativo===false?'Usuário ativado':'Usuário desativado');sync()}).catch(e=>toast(e.message||'Não foi possível alterar o status'))}
function newUserForm(){if(!currentStaff||!['owner','manager'].includes(currentStaff.role))return toast('Somente proprietário ou gerente pode cadastrar usuários.');modal('Novo usuário da equipe',`<div class="form-grid"><label>Nome<input name="nome" maxlength="80" required></label><label>E-mail<input name="email" type="email" autocomplete="off" required></label><label>Senha temporária<input name="password" type="password" minlength="6" autocomplete="new-password" required><small>O Firebase exige no mínimo 6 caracteres. Entregue a senha por canal seguro.</small></label><label>Função<select name="role">${ALLOWED_ROLES.filter(r=>currentStaff.role==='manager'?r!=='owner':true).map(r=>`<option value="${r}">${r}</option>`).join('')}</select></label><div class="notice">A conta é criada em uma sessão Firebase temporária; sua sessão de gestão permanece ativa. Se a gravação do perfil for recusada, a conta temporária é removida quando possível.</div><div class="form-actions"><button type="button" class="secondary" id="cancelForm">Cancelar</button><button class="primary">Criar usuário</button></div></div>`,async f=>{if(!remote)return toast('Cadastro de usuários exige Firebase conectado.');const btn=document.querySelector('#modalForm button.primary');if(btn)btn.disabled=true;try{await window.NONNA_STAFF_AUTH.createStaffAccount({nome:f.get('nome'),email:f.get('email'),password:f.get('password'),role:f.get('role'),restaurantId:currentStaff.restaurantId});toast('Usuário criado e ativo');await sync()}catch(e){toast(e.message||'Não foi possível criar usuário');return false}finally{if(btn)btn.disabled=false}})}
function renderSettings(){const c=settings||{};['Nome','Cnpj','Cor','Cor2','Abertura','Fechamento','Endereco'].forEach(k=>{const el=$('set'+k);if(el)el.value=c[{Nome:'nome',Cnpj:'cnpj',Cor:'corPrimaria',Cor2:'corDestaque',Abertura:'abertura',Fechamento:'fechamento',Endereco:'endereco'}[k]]||({Cor:'#ae8035',Cor2:'#171614'}[k]||'')});$('logoPreview').innerHTML=c.logoData?`<img src="${esc(c.logoData)}" alt="Logo atual">`:'Nenhuma logo definida' }
async function saveSettings(){const file=$('setLogo').files[0];if(file&&file.size>1024*1024)return toast('A logo deve ter até 1 MB');const finish=logo=>{settings={...settings,nome:$('setNome').value.trim(),cnpj:$('setCnpj').value.trim(),corPrimaria:$('setCor').value,corDestaque:$('setCor2').value,abertura:$('setAbertura').value,fechamento:$('setFechamento').value,endereco:$('setEndereco').value.trim(),...(logo?{logoData:logo}:{})};if(remote)await firebase.database().ref('config').update(settings);else localStorage.setItem('donna_config',JSON.stringify(settings));renderSettings();toast('Configurações salvas')};if(file){const fr=new FileReader();fr.onload=()=>finish(fr.result);fr.onerror=()=>toast('Não foi possível ler a logo selecionada.');fr.readAsDataURL(file)}else finish(null)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
async function endDay(){
  if(!currentStaff||!['owner','manager'].includes(currentStaff.role))return toast('Somente gerente ou proprietário pode encerrar o dia.');
  try{
    if(!window.NONNA_STAFF_AUTH?.authorizeCashClosure)throw new Error('Autenticação de gerente indisponível.');
    await window.NONNA_STAFF_AUTH.authorizeCashClosure(currentStaff);
    if(cash&&cash.status==='aberto')throw new Error('Feche o caixa antes de encerrar o dia.');
    const today=new Date();today.setHours(0,0,0,0);
    const dayClosings=closings.filter(c=>{const d=new Date(c.fechadoEm||0);return d>=today&&d<new Date(today.getTime()+86400000)});
    const totalContado=dayClosings.reduce((s,c)=>s+Number(c.valorContado||0),0), totalEsperado=dayClosings.reduce((s,c)=>s+Number(c.valorEsperado||0),0);
    const summary={id:'dia_'+today.toISOString().slice(0,10),data:today.toISOString().slice(0,10),encerradoEm:new Date().toISOString(),encerradoPor:currentStaff.nome||currentStaff.email,fechamentos:dayClosings.length,totalContado,totalEsperado,diferenca:totalContado-totalEsperado};
    if(remote)await firebase.database().ref('gestao/diasEncerrados/'+summary.id).set(summary);else localStorage.setItem('nonna_dia_encerrado_'+summary.data,JSON.stringify(summary));
    $('dailyCloseSummary').hidden=false;$('dailyCloseSummary').innerHTML='<strong>Dia encerrado — '+new Date(today).toLocaleDateString('pt-BR')+'</strong><br>'+dayClosings.length+' fechamento(s) · Contado: '+money(totalContado)+' · Esperado: '+money(totalEsperado)+' · Diferença: '+money(summary.diferenca);
    toast('Dia encerrado e consolidação registrada.');
  }catch(e){toast(e.message||'Não foi possível encerrar o dia.')}
}
function exportCSV(){const rows=[['Data','Status','Canal','Total'],...validOrders().filter(o=>(reportStatus==='all'||String(o.status||'')===reportStatus)&&(reportChannel==='all'||String(o.canal||o.origem||'outro')===reportChannel)).map(o=>[dateOf(o).toISOString(),o.status,o.canal||o.origem||'',Number(o.total||0).toFixed(2)])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n')],{type:'text/csv'}));a.download='relatorio-nonna.csv';a.click();URL.revokeObjectURL(a.href)}
async function startGestao(staff){
  if(startGestao._started)return;
  startGestao._started=true;
  if(staff)currentStaff=staff;
  $('authGate').hidden=true;$('gestaoApp').hidden=false;
  if($('dataAtual'))$('dataAtual').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'});
  document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});$('periodo').onchange=e=>{period=e.target.value;renderAll()};$('reportChannel').onchange=e=>{reportChannel=e.target.value;renderAll()};$('reportStatus').onchange=e=>{reportStatus=e.target.value;renderAll()};$('refresh').onclick=sync;$('newMenuItem').onclick=()=>menuForm();$('newStock').onclick=()=>stockForm();$('newExpense').onclick=expenseForm;$('newReservation').onclick=()=>reservationForm();$('exportReport').onclick=exportCSV;$('refreshUsers').onclick=sync;$('newUser').onclick=newUserForm;$('saveSettings').onclick=saveSettings;$('endDay').onclick=endDay;sync();if(window.DB){DB.onChange(()=>sync())}
}
window.NONNA_GESTAO_START=startGestao;
async function init(){
  const form=$('gestaoLoginForm'), restored=await (window.window.NONNA_STAFF_AUTH?.restore?.()||Promise.resolve(null)).catch(()=>null);
  if(restored){currentStaff=restored;startGestao();return}
  // O formulário é controlado pelo handler do index.html, que autentica
  // antes do boot do banco e evita dois sign-ins concorrentes.
}

function wait(){
  // A falha de leitura inicial do Firebase não pode impedir o login.
  // O usuário autentica primeiro; os dados entram quando o DB ficar pronto.
  if(window.NONNA_STAFF_AUTH && window.firebase?.auth){init()}
  else setTimeout(wait,80)
} wait();
})();
