(()=>{
  let cart=[],all=[],appStarted=false;
  const $=id=>document.getElementById(id);
  const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const cents=v=>Math.round((Number(v)||0)*100);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={dinheiro:'Dinheiro',pix:'Pix',debito:'Débito',credito:'Crédito'};
  async function sha(v){try{if(!window.crypto?.subtle)return v==='Mudar2026#'?'cfa8dabd6587192c8807dbcbace372109f89c51c0b4437d219d4934e630a357a':'';const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}catch(_){return''}}
  function price(p){const v=p.preco??p.price??0;return typeof v==='object'?Math.min(...Object.values(v).map(Number).filter(Number.isFinite)):Number(v)||0}
  function products(){const c=DB.getCardapio()||{},tabela=c.precos_base||DB.CARDAPIO_DEFAULT?.precos_base||{};all=[];['sabores','calzones','bebidas','combos','adicionais'].forEach(cat=>(c[cat]||[]).forEach(p=>{const item={...p,cat};if(cat==='sabores'&&!item.preco&&!item.price)item.preco=tabela[item.id]?.M??0;all.push(item)}));renderProducts()}
  function renderProducts(){const q=($('search').value||'').toLowerCase();$('products').innerHTML=all.filter(p=>(p.nome||p.name||'').toLowerCase().includes(q)).map((p,i)=>`<article class="product"><strong>${esc(p.nome||p.name)}</strong><small>${esc(p.desc||p.descricao||p.cat)}<br><b>${money(price(p))}</b></small><button data-add="${i}">Adicionar</button></article>`).join('')||'<p class="empty">Nenhum produto encontrado.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=all[+b.dataset.add],f=cart.find(x=>x.id===p.id&&x.cat===p.cat);f?f.qtd++:cart.push({...p,qtd:1});renderCart()})}
  function saleTotal(){return cart.reduce((s,p)=>s+price(p)*p.qtd,0)}
  function renderCart(){const total=saleTotal();$('total').textContent=money(total);$('cart').innerHTML=cart.map((p,i)=>`<div class="line"><span>${esc(p.nome||p.name)}<br><small>${p.qtd} × ${money(price(p))}</small></span><button data-minus="${i}">−</button><button data-plus="${i}">+</button></div>`).join('')||'<p class="empty">Nenhum item.</p>';document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.minus].qtd--;if(cart[+b.dataset.minus].qtd<1)cart.splice(+b.dataset.minus,1);renderCart()});document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.plus].qtd++;renderCart()});renderPaymentFields()}
  function renderPaymentFields(){const form=$('payment').value,mixed=form==='misto',box=$('paymentSplit'),saved={};box.querySelectorAll('.split-value').forEach(i=>saved[i.dataset.form]=i.value);box.hidden=false;box.innerHTML='<small>Informe o valor recebido. A soma deve ser exatamente o total.</small>'+(mixed?Object.entries(labels).map(([k,v])=>`<label>${v}<input class="split-value" data-form="${k}" inputmode="decimal" placeholder="R$ 0,00"></label>`).join(''):`<label>${labels[form]}<input class="split-value" data-form="${form}" inputmode="decimal" placeholder="R$ 0,00"></label>`);box.querySelectorAll('.split-value').forEach(i=>{if(saved[i.dataset.form]!=null)i.value=saved[i.dataset.form]})}
  function parseValue(input){let raw=String(input.value||'').trim().replace(/R\$\s?/g,'');if(raw.includes(','))raw=raw.replace(/\./g,'').replace(',','.');if(!raw)return 0;const n=Number(raw);return Number.isFinite(n)&&n>=0?n:NaN}
  function paymentValues(){const form=$('payment').value,inputs=document.querySelectorAll('.split-value');const values={};for(const input of inputs){const n=parseValue(input);if(Number.isNaN(n))return null;if(n>0)values[input.dataset.form]=n}return values}
  function refreshCash(){const c=DB.getCaixaAtual();$('cashState').textContent=c&&c.status==='aberto'?'● Aberto':'● Fechado';$('cashInfo').textContent=c&&c.status==='aberto'?`Abertura: ${money(c.saldoInicial)} · ${c.operador}`:'';$('openCash').disabled=!!(c&&c.status==='aberto');$('closeCash').disabled=!(c&&c.status==='aberto');renderSummary(c)}
  function renderSummary(c){const box=$('closingSummary');if(!c){box.hidden=true;return}const totals={dinheiro:0,pix:0,debito:0,credito:0};let sangria=0,suprimento=0;for(const m of c.movimentos||[]){const v=Number(m.valor)||0;if(m.tipo==='venda'){if(m.forma==='misto'&&m.pagamentos)Object.entries(m.pagamentos).forEach(([f,n])=>{if(totals[f]!=null)totals[f]+=Number(n)||0});else if(totals[m.forma]!=null)totals[m.forma]+=v}else if(m.tipo==='sangria')sangria+=v;else if(m.tipo==='suprimento')suprimento+=v}const esperado=Number(c.saldoInicial||0)+totals.dinheiro+suprimento-sangria;box.hidden=false;box.innerHTML=`<h3>Resumo do ${c.status==='fechado'?'fechamento':'caixa'}</h3><div class="summary-grid">${Object.entries(labels).map(([f,l])=>`<span>${l}</span><strong>${money(totals[f])}</strong>`).join('')}<span>Suprimentos</span><strong>${money(suprimento)}</strong><span>Sangrias</span><strong>− ${money(sangria)}</strong><span>Saldo esperado em dinheiro</span><strong>${money(esperado)}</strong>${c.status==='fechado'?`<span>Valor contado</span><strong>${money(c.valorContado)}</strong>`:''}</div>`}
  async function finish(){const c=DB.getCaixaAtual();if(!c||c.status!=='aberto'){alert('Abra o caixa antes de registrar vendas.');return}if(!cart.length)return;const itens=cart.map(p=>({id:p.id,nome:p.nome||p.name,preco:price(p),quantidade:p.qtd,cat:p.cat})),total=itens.reduce((s,p)=>s+p.preco*p.quantidade,0),values=paymentValues();if(!values){alert('Informe valores válidos para cada forma de pagamento.');return}const sum=Object.values(values).reduce((s,v)=>s+cents(v),0);if(sum!==cents(total)){alert(`Os pagamentos devem somar exatamente ${money(total)}.`);return}const form=$('payment').value;DB.addPedido({cliente:{nome:'Balcão',tel:'balcao',endereco:{tipo:'retirada'}},itens,total,subtotal:total,taxa:0,desconto:0,origem:'balcao',canal:'balcao',createdBy:c.operador,pagamento:{forma,pagamentos:values},pag:form});Object.entries(values).forEach(([f,v])=>DB.registrarMovimentoCaixa({tipo:'venda',valor:v,forma:f,operador:c.operador}));cart=[];renderCart();alert('Venda registrada com sucesso.')}
  function init(){const form=$('loginForm');form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);let valido=false;try{valido=String(f.get('user')).trim().toLowerCase()==='caixa'&&await sha(f.get('pass'))==='cfa8dabd6587192c8807dbcbace372109f89c51c0b4437d219d4934e630a357a'}catch(_){valido=false}if(!valido){$('err').textContent='Usuário ou senha inválidos. Confira os dados e tente novamente.';return}sessionStorage.setItem('nonna_caixa','ok');start()};if(sessionStorage.getItem('nonna_caixa')==='ok')start()}
  function start(){$('login').hidden=true;$('app').hidden=false;if(typeof DB==='undefined'||typeof DB.getCardapio!=='function'){$('cashInfo').textContent='Conectando ao banco de dados…';setTimeout(start,500);return}if(appStarted)return;appStarted=true;$('operator').textContent='Operador Caixa';$('search').oninput=renderProducts;$('payment').onchange=renderPaymentFields;$('finish').onclick=finish;$('openCash').onclick=()=>{const v=prompt('Valor inicial do caixa:','0');if(v!==null)DB.abrirCaixa({operador:'Caixa',saldoInicial:v});refreshCash()};$('withdraw').onclick=()=>{const v=prompt('Valor da sangria:');if(v)DB.registrarMovimentoCaixa({tipo:'sangria',valor:v,operador:'Caixa'});refreshCash()};$('supply').onclick=()=>{const v=prompt('Valor do suprimento:');if(v)DB.registrarMovimentoCaixa({tipo:'suprimento',valor:v,operador:'Caixa'});refreshCash()};$('closeCash').onclick=()=>{const v=prompt('Valor contado no fechamento:');if(v!==null){DB.fecharCaixa({operador:'Caixa',valorContado:v});refreshCash()}};DB.onChange(()=>{products();refreshCash()});products();renderCart();refreshCash()}
  window.init=init
})();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>window.init&&window.init());else setTimeout(()=>window.init&&window.init(),0);
