(()=>{
  let cart=[],all=[],appStarted=false,staff=null;
  const $=id=>document.getElementById(id);
  const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const cents=v=>Math.round((Number(v)||0)*100);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={dinheiro:'Dinheiro',pix:'Pix',debito:'Débito',credito:'Crédito'};
  function price(p){const v=p.preco??p.price??0;if(v&&typeof v==='object'){const n=Number(v.M??v.G??v.P??Object.values(v)[0]??0);return Number.isFinite(n)?n:0}return Number(v)||0}
  function products(){const c=DB.getCardapio()||{},tabela=c.precos_base||DB.CARDAPIO_DEFAULT?.precos_base||{};all=[];if($('coupon'))$('coupon').innerHTML='<option value="">Cupom da Gestão</option>'+((c.cupons||[]).filter(x=>x&&x.codigo).map(x=>`<option value="${esc(x.codigo)}">${esc(x.codigo)} — ${esc(x.desc||'desconto')}</option>`).join(''));['sabores','calzones','bebidas','combos','adicionais'].forEach(cat=>(c[cat]||[]).forEach(p=>{const item={...p,cat};if(cat==='sabores'&&!item.preco&&!item.price)item.preco=tabela[item.id]?.M??0;all.push(item)}));renderProducts()}
  function renderProducts(){const q=($('search').value||'').toLowerCase(),names={sabores:'Pizzas',calzones:'Calzones',bebidas:'Bebidas',combos:'Combos',adicionais:'Adicionais'},cats=[...new Set(all.map(p=>p.cat))],active=window._caixaCat||cats[0];$('cats').innerHTML=cats.map(c=>`<button class="cat-btn ${c===active?'active':''}" data-cat="${esc(c)}">${names[c]||c}</button>`).join('');const shown=all.filter(p=>p.cat===active&&(p.nome||p.name||'').toLowerCase().includes(q));$('products').innerHTML=shown.map((p,i)=>`<article class="product"><strong>${esc(p.nome||p.name)}</strong><small>${esc(p.desc||p.descricao||p.cat)}<br><b>${money(price(p))}</b></small><button data-add="${i}">Adicionar</button></article>`).join('')||'<p class="empty">Nenhum produto encontrado.</p>';document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{window._caixaCat=b.dataset.cat;renderProducts()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=shown[+b.dataset.add];if(p.cat==='sabores')return pizzaFlow(p);const f=cart.find(x=>x.id===p.id&&x.cat===p.cat);f?f.qtd++:cart.push({...p,qtd:1});renderCart()})}
  function pizzaFlow(first){const sizes=DB.getCardapio()?.tamanhos||DB.CARDAPIO_DEFAULT.tamanhos||[],raw=prompt('Tamanho da pizza (P, M ou G):','M');if(!raw)return;const sz=sizes.find(x=>String(x.id).toUpperCase()===raw.trim().toUpperCase())||sizes.find(x=>x.id==='M');if(!sz){alert('Tamanho inválido.');return}const names=prompt(`Sabores (separe por vírgula; até ${sz.qtdSabores||1}):`,first.nome);if(!names)return;const chosen=names.split(',').map(x=>x.trim()).filter(Boolean).slice(0,Number(sz.qtdSabores||1));const items=all.filter(x=>x.cat==='sabores'),fl=chosen.map(n=>items.find(x=>(x.nome||'').toLowerCase()===n.toLowerCase())||first),base=fl.reduce((a,x)=>a+price(x),0)/fl.length;cart.push({id:'pizza_'+Date.now(),nome:`Pizza ${sz.nome}: ${fl.map(x=>x.nome).join(' / ')}`,preco:Math.round(base*100)/100,cat:'pizza',qtd:1,pizza:{tamanho:sz.id,sabores:fl.map(x=>x.id)}});renderCart()}
  function saleSubtotal(){return cart.reduce((s,p)=>s+price(p)*p.qtd,0)}
  function discountInfo(sub){const type=$('discountType')?.value||'none',v=Number($('discountValue')?.value||0),coupon=(DB.getCardapio()?.cupons||[]).find(c=>String(c.codigo).toUpperCase()===(($('coupon')?.value||'').toUpperCase()));let d=type==='amount'?Math.min(sub,Math.max(0,v)):type==='percent'?Math.min(sub,sub*Math.min(100,Math.max(0,v))/100):0;if(coupon)d=Math.max(d,coupon.tipo==='percentual'?sub*Math.min(100,Number(coupon.valor)||0)/100:Math.min(sub,Number(coupon.valor)||0));return {desconto:d,total:Math.max(0,sub-d)}}
  function saleTotal(){return discountInfo(saleSubtotal()).total}
  function renderCart(){const sub=saleSubtotal(),info=discountInfo(sub),total=info.total;$('total').textContent=money(total);$('cart').innerHTML=cart.map((p,i)=>`<div class="line"><span>${esc(p.nome||p.name)}<br><small>${p.qtd} × ${money(price(p))}</small></span><button data-minus="${i}">−</button><button data-plus="${i}">+</button></div>`).join('')||'<p class="empty">Nenhum item.</p>';document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.minus].qtd--;if(cart[+b.dataset.minus].qtd<1)cart.splice(+b.dataset.minus,1);renderCart()});document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.plus].qtd++;renderCart()});renderPaymentFields()}
  function renderPaymentFields(){const form=$('payment').value,mixed=form==='misto',box=$('paymentSplit'),saved={};box.querySelectorAll('.split-value').forEach(i=>saved[i.dataset.form]=i.value);box.hidden=false;box.innerHTML='<small>Informe o valor recebido. A soma deve ser exatamente o total.</small>'+(mixed?Object.entries(labels).map(([k,v])=>`<label>${v}<input class="split-value" data-form="${k}" inputmode="decimal" placeholder="R$ 0,00"></label>`).join(''):`<label>${labels[form]}<input class="split-value" data-form="${form}" inputmode="decimal" placeholder="R$ 0,00"></label>`);box.querySelectorAll('.split-value').forEach(i=>{if(saved[i.dataset.form]!=null)i.value=saved[i.dataset.form]})}
  function parseValue(input){let raw=String(input.value||'').trim().replace(/R\$\s?/g,'');if(raw.includes(','))raw=raw.replace(/\./g,'').replace(',','.');if(!raw)return 0;const n=Number(raw);return Number.isFinite(n)&&n>=0?n:NaN}
  function paymentValues(){const form=$('payment').value,inputs=document.querySelectorAll('.split-value');const values={};for(const input of inputs){const n=parseValue(input);if(Number.isNaN(n))return null;if(n>0)values[input.dataset.form]=n}return values}
  function refreshCash(){const c=DB.getCaixaAtual();$('cashState').textContent=c&&c.status==='aberto'?'● Aberto':'● Fechado';$('cashInfo').textContent=c&&c.status==='aberto'?`Abertura: ${money(c.saldoInicial)} · ${c.operador}`:'';$('openCash').disabled=!!(c&&c.status==='aberto');$('closeCash').disabled=!(c&&c.status==='aberto');renderSummary(c)}
  function renderSummary(c){const box=$('closingSummary');if(!c){box.hidden=true;return}const totals={dinheiro:0,pix:0,debito:0,credito:0};let sangria=0,suprimento=0;for(const m of c.movimentos||[]){const v=Number(m.valor)||0;if(m.tipo==='venda'){if(m.forma==='misto'&&m.pagamentos)Object.entries(m.pagamentos).forEach(([f,n])=>{if(totals[f]!=null)totals[f]+=Number(n)||0});else if(totals[m.forma]!=null)totals[m.forma]+=v}else if(m.tipo==='sangria')sangria+=v;else if(m.tipo==='suprimento')suprimento+=v}const esperado=Number(c.saldoInicial||0)+totals.dinheiro+suprimento-sangria;box.hidden=false;box.innerHTML=`<h3>Resumo do ${c.status==='fechado'?'fechamento':'caixa'}</h3><div class="summary-grid">${Object.entries(labels).map(([f,l])=>`<span>${l}</span><strong>${money(totals[f])}</strong>`).join('')}<span>Suprimentos</span><strong>${money(suprimento)}</strong><span>Sangrias</span><strong>− ${money(sangria)}</strong><span>Saldo esperado em dinheiro</span><strong>${money(esperado)}</strong>${c.status==='fechado'?`<span>Valor contado</span><strong>${money(c.valorContado)}</strong>`:''}</div>`}
  async function finish(){const c=DB.getCaixaAtual();if(!c||c.status!=='aberto'){alert('Abra o caixa antes de registrar vendas.');return}if(!cart.length)return;const itens=cart.map(p=>({id:p.id,nome:p.nome||p.name,preco:price(p),quantidade:p.qtd,cat:p.cat,pizza:p.pizza||null})),subtotal=itens.reduce((s,p)=>s+p.preco*p.quantidade,0),di=discountInfo(subtotal),manualType=$('discountType')?.value||'none',manualValue=Number($('discountValue')?.value||0);let discountAuth=null;if(di.desconto>0&&['amount','percent'].includes(manualType)&&manualValue>0){try{discountAuth=await window.NONNA_STAFF_AUTH.authorizeDiscount(staff)}catch(err){alert(err.message||'Desconto manual não autorizado.');return}}const total=di.total,values=paymentValues();if(!values){alert('Informe valores válidos para cada forma de pagamento.');return}const sum=Object.values(values).reduce((s,v)=>s+cents(v),0);if(sum!==cents(total)){alert(`Os pagamentos devem somar exatamente ${money(total)}.`);return}const form=$('payment').value;await DB.addPedido({cliente:{nome:'Balcão',tel:'balcao',endereco:{tipo:'retirada'}},itens,total,subtotal:subtotal,taxa:0,desconto:di.desconto,descontoAutorizadoPor:discountAuth?{uid:discountAuth.uid,email:discountAuth.email,role:discountAuth.role}:null,origem:'balcao',cupom:$('coupon')?.value||null,canal:'balcao',createdBy:c.operador,pagamento:{forma,pagamentos:values},pag:form});for(const [f,v] of Object.entries(values)) await DB.registrarMovimentoCaixa({tipo:'venda',valor:v,forma:f,operador:c.operador});cart=[];if($('discountValue'))$('discountValue').value='';renderCart();refreshCash();renderTables();alert('Venda registrada com sucesso.')}
  function mesaDo(p){return String(p?.mesa??p?.endereco?.mesa??'').trim()}
  function openSalon(){const by={};(DB.getPedidos()||[]).filter(p=>mesaDo(p)&&!p.contaFechada&&!['cancelado','cancelada','cancelled','fechado'].includes(String(p.status||'').toLowerCase())).forEach(p=>(by[mesaDo(p)]??=[]).push(p));$('tableComandas').innerHTML=Object.entries(by).map(([mesa,ps])=>{const total=ps.reduce((a,p)=>a+Number(p.total||0),0);return `<div class="table-account"><strong>Mesa ${esc(mesa)}</strong><span>${ps.length} pedido(s) · ${money(total)}</span><button data-close-table="${esc(mesa)}">Fechar conta</button></div>`}).join('')||'<p class="empty">Nenhuma comanda aberta.</p>';document.querySelectorAll('[data-close-table]').forEach(b=>b.onclick=()=>closeSalon(b.dataset.closeTable))}
  function renderTables(){if($('tableComandas'))openSalon()}
  async function closeSalon(mesa){const ps=(DB.getPedidos()||[]).filter(p=>mesaDo(p)===String(mesa)&&!p.contaFechada&&!['cancelado','cancelada','fechado'].includes(String(p.status||'').toLowerCase()));if(!ps.length)return;const total=ps.reduce((a,p)=>a+Number(p.total||0),0),forma=prompt('Forma de pagamento: Dinheiro, Pix, Débito ou Crédito','Pix');if(!forma)return;if(!confirm(`Fechar a conta da Mesa ${mesa} no valor de ${money(total)}?`))return;try{for(const p of ps)await DB.updatePedido(p.id,{contaFechada:true,formaPagamento:forma.trim().toLowerCase(),fechadaEm:new Date().toISOString(),status:'fechado',operacaoSalao:'fechamento_caixa'});await DB.registrarMovimentoCaixa({tipo:'venda',valor:total,forma:forma.trim().toLowerCase(),operador:staff?.nome||'Caixa'});renderTables();refreshCash()}catch(e){alert(e.message||'Não foi possível fechar a conta.')}}
  async function init(){
    const form=$('loginForm');
    const restored=await (window.window.NONNA_STAFF_AUTH?.restore?.()||Promise.resolve(null)).catch(()=>null);
    if(restored){staff=restored;start();return}
    form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form),btn=form.querySelector('button');$('err').textContent='';btn.disabled=true;btn.textContent='Entrando…';try{staff=await NONNA_STAFF_AUTH.signIn(String(f.get('user')).trim(),String(f.get('pass')));start()}catch(err){$('err').textContent=err.message||'Não foi possível entrar.'}finally{btn.disabled=false;btn.textContent='Entrar'}};
  }
  function bind(){if(appStarted)return;if(typeof DB==='undefined'||typeof DB.getCardapio!=='function'||!DB._ready){$('cashInfo').textContent='Aguardando conexão segura com o banco…';$('cashState').textContent='● Conectando';return}appStarted=true;$('operator').textContent=staff?.nome||staff?.email||'Operador';$('search').oninput=renderProducts;$('discountType').onchange=renderCart;$('discountValue').oninput=renderCart;$('coupon').onchange=renderCart;$('refreshTables').onclick=renderTables;$('payment').onchange=renderPaymentFields;$('finish').onclick=async()=>{const b=$('finish');if(b.dataset.busy==='1')return;b.dataset.busy='1';b.disabled=true;try{await finish()}finally{delete b.dataset.busy;b.disabled=false}};$('openCash').onclick=async()=>{const v=prompt('Valor inicial do caixa:','0');if(v!==null){try{await DB.abrirCaixa({operador:staff?.nome||staff?.email||'Caixa',saldoInicial:v});refreshCash()}catch(e){alert(e.message||'Não foi possível abrir o caixa.')}}};$('withdraw').onclick=async()=>{const v=prompt('Valor da sangria:');if(v){try{await DB.registrarMovimentoCaixa({tipo:'sangria',valor:v,operador:staff?.nome||staff?.email||'Caixa'});refreshCash()}catch(e){alert(e.message||'Não foi possível registrar a sangria.')}}};$('supply').onclick=async()=>{const v=prompt('Valor do suprimento:');if(v){try{await DB.registrarMovimentoCaixa({tipo:'suprimento',valor:v,operador:staff?.nome||staff?.email||'Caixa'});refreshCash()}catch(e){alert(e.message||'Não foi possível registrar o suprimento.')}}};$('closeCash').onclick=async()=>{const c=DB.getCaixaAtual();if(!c||c.status!=='aberto')return;try{if(!window.NONNA_STAFF_AUTH?.authorizeCashClosure)throw new Error('Não foi possível validar a senha de fechamento.');const auth=await window.NONNA_STAFF_AUTH.authorizeCashClosure(staff);const v=prompt('Valor contado no fechamento:');if(v===null)return;await DB.fecharCaixa({operador:auth.nome||auth.email,valorContado:v});refreshCash()}catch(e){alert(e.message||'Não foi possível fechar o caixa.')}};DB.onChange(()=>{products();refreshCash()});products();renderCart();refreshCash();renderTables();window.addEventListener('nonna_db_ready',()=>{products();refreshCash()});window.addEventListener('nonna_connection_change',()=>refreshCash())}
  function start(){ $('login').hidden=true;$('app').hidden=false;if(typeof DB!=='undefined'&&DB._ready)bind();else{const ready=window.NONNA_DB_READY;if(ready&&typeof ready.then==='function')ready.then(bind).catch(()=>{$('cashInfo').textContent='Não foi possível conectar ao banco. Recarregue e tente novamente.';$('cashState').textContent='● Erro de conexão'});else window.addEventListener('nonna_db_ready',bind,{once:true});}}
  window.init=init
})();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>window.init&&window.init());else setTimeout(()=>window.init&&window.init(),0);
