(()=>{let cart=[],ready=false,staff=null;const TABLES=Array.from({length:12},(_,i)=>String(i+1));const $=id=>document.getElementById(id);const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const hash=async v=>{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')};
async function open(){
 if(window.NONNA_STAFF_AUTH){
  try{staff=await NONNA_STAFF_AUTH.restore()}catch(_){staff=null}
  if(staff){ready=true;$('loginScreen').hidden=true;$('appScreen').hidden=false;render();return}
 }
 $('loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),btn=e.target.querySelector('button');$('loginError').textContent='';btn.disabled=true;btn.textContent='Entrando…';try{staff=await NONNA_STAFF_AUTH.signIn(String(f.get('user')).trim(),String(f.get('password')));ready=true;$('loginScreen').hidden=true;$('appScreen').hidden=false;render()}catch(err){$('loginError').textContent=err.message||'Não foi possível entrar.'}finally{btn.disabled=false;btn.textContent='Entrar'}}
}
function items(){const c=DB.getCardapio()||{},out=[];const tabela=c.precos_base||DB.CARDAPIO_DEFAULT?.precos_base||{};['sabores','calzones','bebidas','combos','adicionais'].forEach(cat=>(c[cat]||[]).forEach(p=>{const item={...p,cat};if(cat==='sabores'&&!item.preco&&!item.price)item.preco=tabela[item.id]?.M??0;out.push(item)}));return out}
function render(){const m=items();const cats=[...new Set(m.map(p=>p.cat))];const names={sabores:'Pizzas',calzones:'Calzones',bebidas:'Bebidas',combos:'Combos',adicionais:'Adicionais'};const active=window._garcomCat||cats[0];$('menuCategories').innerHTML=cats.map(c=>`<button class="category-btn ${c===active?'active':''}" data-cat="${esc(c)}">${names[c]||c}</button>`).join('');const shown=m.filter(p=>p.cat===active);$('menu').innerHTML=shown.map((p,i)=>`<article class="menu-item"><div class="grow"><strong>${esc(p.nome||p.name||'Produto')}</strong><small>${esc(p.desc||p.descricao||p.cat)}</small><b class="price">${money(price(p))}</b></div><button class="add" data-add="${i}" aria-label="Adicionar ${esc(p.nome||p.name)}">+</button></article>`).join('')||'<p class="empty">Nenhum item nesta categoria.</p>';document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{window._garcomCat=b.dataset.cat;render()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=shown[Number(b.dataset.add)];if(p.cat==='sabores')return pizzaFlow(p,m);const found=cart.find(x=>x.id===p.id&&x.cat===p.cat);if(found)found.qtd++;else cart.push({...p,qtd:1});renderCart()});renderCart();renderTables();renderAccounts()}
function pizzaFlow(first,all){const sizes=DB.getCardapio()?.tamanhos||DB.CARDAPIO_DEFAULT.tamanhos||[];const size=prompt('Tamanho da pizza (P, M ou G):','M');if(!size)return;const sz=sizes.find(x=>String(x.id).toUpperCase()===size.trim().toUpperCase())||sizes.find(x=>x.id==='M');if(!sz){alert('Tamanho inválido.');return}const max=Number(sz.qtdSabores||1);const raw=prompt(`Sabores (separe por vírgula; até ${max}):`,first.nome);if(!raw)return;const names=raw.split(',').map(x=>x.trim()).filter(Boolean).slice(0,max);const chosen=names.map(n=>all.find(x=>x.cat==='sabores'&&(x.nome||'').toLowerCase()===n.toLowerCase())||first);const base=chosen.reduce((sum,x)=>sum+price(x),0)/chosen.length;const item={id:'pizza_'+Date.now(),nome:`Pizza ${sz.nome}: ${chosen.map(x=>x.nome).join(' / ')}`,preco:Math.round(base*100)/100,cat:'pizza',pizza:{tamanho:sz.id,sabores:chosen.map(x=>x.id)}};cart.push({...item,qtd:1});renderCart()}
function showComanda(mesa){const ps=ordersFor(mesa);$('comandaTitle').textContent='— Mesa '+mesa;$('comandaBody').innerHTML=ps.length?ps.map(p=>`<div class="comanda-order"><strong>${esc(p.cliente?.nome||'Pedido')}</strong><small>${(p.itens||[]).map(i=>`${esc(i.nome||i.name)} × ${Number(i.quantidade||i.qtd||1)}`).join('<br>')}</small><b>${money(p.total)}</b></div>`).join(''):'<p class="empty">Nenhum pedido aberto.</p>';$('comandaModal').hidden=false}

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function price(p){const v=p.preco??p.price??0;if(v&&typeof v==='object')return Math.min(...Object.values(v).map(Number).filter(Number.isFinite));return Number(v)||0}
function renderCart(){const total=cart.reduce((s,p)=>s+price(p)*p.qtd,0);$('cartCount').textContent=`${cart.reduce((s,p)=>s+p.qtd,0)} itens`;$('cartTotal').textContent=money(total);$('cartItems').innerHTML=cart.map((p,i)=>`<div class="cart-line"><span class="grow">${esc(p.nome||p.name)}<small>${money(price(p))}</small></span><span class="qty"><button data-minus="${i}">−</button>${p.qtd}<button data-plus="${i}">+</button></span></div>`).join('')||'<p class="empty">Nenhum item selecionado.</p>';document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.minus].qtd--;if(cart[+b.dataset.minus].qtd<1)cart.splice(+b.dataset.minus,1);renderCart()});document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.plus].qtd++;renderCart()})}
function mesaDo(p){return String(p?.mesa??p?.endereco?.mesa??'').trim()}function ordersFor(mesa){return(DB.getPedidos()||[]).filter(p=>p&&mesaDo(p)===String(mesa)&&!p.contaFechada&&!['cancelado','cancelada','cancelled'].includes(normalize(p.status)))}function normalize(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[ -]/g,'_')}
function tableState(ps){if(!ps.length)return'free';if(ps.some(p=>p.aguardandoConta||p.contaSolicitada||['aguardando_conta','conta_solicitada'].includes(normalize(p.status))))return'bill';const terminal=['entregue','concluido','concluida','finalizado','finalizada','retirado','fechado'];return ps.every(p=>terminal.includes(normalize(p.status)))?'bill':'busy'}function labelState(s){return s==='free'?'Livre':s==='bill'?'Aguardando conta':'Ocupada'}
function renderTables(){const map=$('tableMap');if(!map)return;const all=new Set(TABLES);(DB.getPedidos()||[]).forEach(p=>{const m=mesaDo(p);if(m&&!p.contaFechada)all.add(m)});const data=[...all].sort((a,b)=>Number(a)-Number(b)||a.localeCompare(b,'pt-BR')).map(m=>{const ps=ordersFor(m),state=tableState(ps),total=ps.reduce((s,p)=>s+Number(p.total||0),0);return{m,ps,state,total}});const counts=data.reduce((o,x)=>(o[x.state]++,o),{free:0,busy:0,bill:0});$('tableSummary').innerHTML=`<span><b>${counts.free}</b> livres</span><span><b>${counts.busy}</b> ocupadas</span><span><b>${counts.bill}</b> aguardando conta</span>`;map.innerHTML=data.map(x=>`<article class="table-seat state-${x.state}"><div class="table-seat-top"><strong>Mesa ${esc(x.m)}</strong><span class="table-status">${labelState(x.state)}</span></div><div class="table-shape"><span>${x.ps.length?x.ps.length+' pedido(s)':'Sem pedidos'}</span></div><div class="table-seat-bottom"><b>${x.total?money(x.total):'—'}</b><button class="table-select" data-table="${esc(x.m)}">${x.state==='free'?'Selecionar':'Ver comanda'}</button></div></article>`).join('');map.querySelectorAll('[data-table]').forEach(b=>b.onclick=()=>selectTable(b.dataset.table))}
function selectTable(mesa){if(ordersFor(mesa).length)showComanda(mesa);else{$('mesa').value=mesa;$('mesa').focus();$('menu').scrollIntoView({behavior:'smooth',block:'start'})}}
function renderAccounts(){const by={};(DB.getPedidos()||[]).filter(p=>mesaDo(p)&&!p.contaFechada&&!['cancelado','cancelada','cancelled'].includes(normalize(p.status))).forEach(p=>{const k=mesaDo(p);(by[k]??=[]).push(p)});$('accountsList').innerHTML=Object.entries(by).map(([mesa,ps])=>{const total=ps.reduce((s,p)=>s+Number(p.total||0),0),split=ps.find(p=>p.contaDivisao)?.contaDivisao;return `<div class="account-row"><span class="grow"><strong>Mesa ${esc(mesa)}</strong><small>${ps.length} pedido(s) · ${ps.map(p=>esc(p.cliente?.nome||'Pedido')).join(', ')}${split?` · ${split.partes} partes de ${money(split.valorPorParte)}`:''}</small></span><span class="account-total">${money(total)}</span><span class="account-actions"><button class="account-action" data-action="transfer" data-table="${esc(mesa)}">Transferir</button><button class="account-action" data-action="merge" data-table="${esc(mesa)}">Unir mesas</button><button class="account-action" data-action="split" data-table="${esc(mesa)}">Dividir conta</button><button class="account-action" data-action="bill" data-table="${esc(mesa)}">Pedir conta</button></span></div>`}).join('')||'<p class="empty">Nenhuma conta aberta.</p>';document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>operacaoConta(b.dataset.action,b.dataset.table))}
async function atualizarPedidos(ps,patch){const result=await Promise.all(ps.map(p=>DB.updatePedido(p.id,patch)));if(result.some(p=>!p))throw new Error('Um dos pedidos não foi encontrado no banco compartilhado.');return result}
async function operacaoConta(acao,mesa){const ps=ordersFor(mesa);if(!ps.length){alert('Não há pedidos abertos nessa mesa.');return}const agora=new Date().toISOString();try{if(acao==='transfer'){const destino=prompt(`Transferir Mesa ${mesa} para qual mesa?`,mesa);if(!destino||!destino.trim()||destino.trim()===String(mesa))return;const d=destino.trim();if(ordersFor(d).length&&!confirm(`A Mesa ${d} já possui pedidos. Transferir mesmo assim?`))return;await atualizarPedidos(ps,{mesa:d,endereco:{mesa:d},mesaAnterior:mesa,operacaoSalao:'transferencia',operacaoEm:agora});alert(`Pedido(s) transferido(s) para a Mesa ${d}.`)}else if(acao==='merge'){const destino=prompt(`Unir a Mesa ${mesa} com qual mesa?`);if(!destino||!destino.trim()||destino.trim()===String(mesa))return;const d=destino.trim();if(!ordersFor(d).length){alert(`A Mesa ${d} não tem uma conta aberta. Use Transferir para movê-la.`);return}if(!confirm(`Os pedidos da Mesa ${mesa} serão incorporados à Mesa ${d}. Continuar?`))return;await atualizarPedidos(ps,{mesa:d,endereco:{mesa:d},mesaAnterior:mesa,operacaoSalao:'uniao_mesas',operacaoEm:agora});alert(`Mesas unidas na Mesa ${d}.`)}else if(acao==='split'){const total=ps.reduce((s,p)=>s+Number(p.total||0),0),raw=prompt(`Dividir ${money(total)} em quantas partes?`),partes=Number(raw);if(!Number.isInteger(partes)||partes<2||partes>99){if(raw!==null)alert('Informe um número inteiro entre 2 e 99.');return}await atualizarPedidos(ps,{contaDividida:true,contaDivisao:{partes,valorTotal:total,valorPorParte:Math.round(total/partes*100)/100,registradaEm:agora},operacaoSalao:'divisao_conta'});alert(`Conta dividida em ${partes} partes de ${money(total/partes)}.`)}else if(acao==='bill'){if(!confirm(`Solicitar a conta da Mesa ${mesa}?`))return;await atualizarPedidos(ps,{status:'aguardando_conta',aguardandoConta:true,contaSolicitada:true,contaSolicitadaEm:agora,operacaoSalao:'solicitacao_conta'});alert('Conta solicitada.')}render()}catch(e){alert(e.message||'Não foi possível concluir a operação.')}}
async function lancar(){const mesa=$('mesa').value.trim(),msg=$('orderMessage');msg.textContent='';if(!mesa){msg.textContent='Informe a mesa.';return}if(!cart.length){msg.textContent='Selecione pelo menos um item.';return}try{await DB.addPedido({cliente:{nome:'Mesa '+mesa,tel:'salão',endereco:{mesa}},mesa,itens:cart.map(p=>({id:p.id,nome:p.nome||p.name,preco:price(p),quantidade:p.qtd,cat:p.cat})),endereco:{mesa},origem:'salao'});cart=[];renderCart();renderTables();renderAccounts();msg.textContent='Pedido lançado com sucesso.'}catch(e){msg.textContent=e.message||'Não foi possível lançar o pedido.'}}
async function init(){if(ready)return;DB.onChange(()=>{if(ready)render()});$('sendOrder').onclick=lancar;$('refresh').onclick=render;$('logout').onclick=async()=>{try{await firebase.auth().signOut()}catch(_){}staff=null;ready=false;$('appScreen').hidden=true;$('loginScreen').hidden=false;$('loginForm').reset();$('loginError').textContent=''};$('closeComanda').onclick=()=>{$('comandaModal').hidden=true};open()}window.init=init})();